language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - nightly

before_script:
  - composer install --prefer-dist --dev

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

script: ./vendor/phpunit/phpunit/phpunit --stderr
